[project]
name = 'ai-powered-practice-companion'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.adaptive-curriculum-builder]
path = 'contracts/adaptive-curriculum-builder.clar'
clarity_version = 3
epoch = 3.1

[contracts.performance-analysis-engine]
path = 'contracts/performance-analysis-engine.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
